### ISSUE TITLE
Avoid the possibility that android's physical back button pops the loading

### ISSUE THREAD

**Issue by cmorsucci** [ajomuch92/simple-fontelico-progress-dialog-flutter#2]
I think it is enough to do such a thing to prevent the physical back button of android hiding the loading modal
into showDialog function...

builder: (BuildContext context) {
return WillPopScope(
onWillPop: () => Future.value(barrierDimisable),
child: Dialog(...)
);
}

**Comment by ajomuch92** [comment]
Thank you sir for noticing this bug, it was fixed in the latest version released today. You can see it [here](https://pub.dev/packages/simple_fontellico_progress_dialog/versions/0.1.5).
