### ISSUE TITLE
After Update Flutter 2.10.0, getting error :(

### ISSUE THREAD

**Issue by skylastn** [ajomuch92/simple-fontelico-progress-dialog-flutter#5]
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Container(bg: BoxDecoration(color: Color(0xffffffff), borderRadius: BorderRadius.circular(5.0)), constraints: BoxConstraints(w=120.0, h=100.0)):
This widget has been unmounted, so the State no longer has a context (and should be considered defunct). 

Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.
The relevant error-causing widget was: 
  GetMaterialApp GetMaterialApp:file:///D:/Kerja/Me/sky_tronik/lib/main.dart:136:14
When the exception was thrown, this was the stack: 
#0      State.context.<anonymous closure> (package:flutter/src/widgets/framework.dart:942:9)
#1      State.context (package:flutter/src/widgets/framework.dart:948:6)
#2      SingleTickerProviderStateMixin._updateTickerModeNotifier (package:flutter/src/widgets/ticker_provider.dart:246:68)
#3      SingleTickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:199:5)
#4      new AnimationController (package:flutter/src/animation/animation_controller.dart:246:21)
#5      new _RotateIconState (package:simple_fontellico_progress_dialog/rotate_icon.dart:26:32)
#6      RotateIcon.createState (package:simple_fontellico_progress_dialog/rotate_icon.dart:11:7)
#7      new StatefulElement (package:flutter/src/widgets/framework.dart:4842:25)
#8      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:770:38)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3785:40)
#10     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#11     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (292 frames)
#303    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#304    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#305    Element.updateChild (package:flutter/src/widgets/framework.dart:3540:18)
#306    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5845:32)
#307    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6445:17)
#308    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#309    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#310    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#311    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#312    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#313    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#314    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#315    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#316    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#317    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#318    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#319    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#320    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#321    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:111:11)
#322    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#323    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#324    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#325    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#326    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#327    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#328    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#329    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#330    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#331    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#332    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#333    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#334    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#335    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#336    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#337    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#338    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#339    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#340    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#341    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#342    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#343    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#344    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#345    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#346    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#350    _invoke (dart:ui/hooks.dart:151:10)
#351    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#352    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================
I/flutter ( 9065): {"status":false,"info":"Mohon maaf, Email anda belum terdaftar di sistem kami"}

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#dcd1f](state: OverlayState#37303(tickers: tracking 0 tickers, entries: [OverlayEntry#a8f06(opaque: true; maintainState: false), OverlayEntry#f395c(opaque: false; maintainState: true), OverlayEntry#ba1e5(opaque: true; maintainState: false), OverlayEntry#f7f51(opaque: false; maintainState: true), OverlayEntry#7e6ed(opaque: false; maintainState: false), OverlayEntry#d7054(opaque: false; maintainState: true)])):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5219 pos 14: '_dependents.isEmpty': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  GetMaterialApp GetMaterialApp:file:///D:/Kerja/Me/sky_tronik/lib/main.dart:136:14
When the exception was thrown, this was the stack: 
#2      InheritedElement.debugDeactivated.<anonymous closure> (package:flutter/src/widgets/framework.dart:5219:14)
#3      InheritedElement.debugDeactivated (package:flutter/src/widgets/framework.dart:5221:6)
#4      _InactiveElements._deactivateRecursively.<anonymous closure> (package:flutter/src/widgets/framework.dart:1948:15)
#5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1950:6)
#6      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#7      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#9      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#11     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#12     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#13     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#15     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#17     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#18     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#19     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#20     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#21     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#23     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#24     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#25     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#27     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#28     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#29     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#30     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#31     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#33     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#34     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#35     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#36     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#37     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#38     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#39     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#40     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#41     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#42     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#43     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#44     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#45     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#46     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#47     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#48     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#49     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#51     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#52     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#53     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#54     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#55     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#56     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#57     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#58     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#59     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#60     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#61     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#62     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#63     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#64     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#65     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#66     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#67     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#69     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#70     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#71     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#72     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#73     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#75     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#76     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#77     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#78     _InactiveElements.add (package:flutter/src/widgets/framework.dart:1958:7)
#79     Element.deactivateChild (package:flutter/src/widgets/framework.dart:3826:30)
#80     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5880:11)
#81     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6445:17)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#84     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#86     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#87     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#88     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#89     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#90     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#91     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#95     _invoke (dart:ui/hooks.dart:151:10)
#96     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#97     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================

**Comment by Ticunas** [comment]
Same here

**Comment by ajomuch92** [comment]
Fixed
